services:
  proxy:
    image: openresty/openresty:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./config.lua:/app/config.lua:ro
      - ./src/proxy.lua:/usr/local/openresty/nginx/conf/proxy.lua:ro
      - ./src/metrics.lua:/usr/local/openresty/nginx/conf/metrics.lua:ro
    restart: unless-stopped