services:
  proxy:
    image: openresty/openresty:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/:/usr/local/openresty/nginx/conf/:ro
    env_file:
      - .env
    restart: unless-stopped