#!/bin/sh
set -e

# ── Ollagate — OpenResty gateway for Ollama Cloud ──

GEN_DIR="/tmp/ollagate"
CONFIG_LUA="${GEN_DIR}/config.lua"

mkdir -p "${GEN_DIR}"

# ── Scan environment for API_KEY_* variables ──

api_var_names=$(env | grep '^API_KEY_' | cut -d= -f1 | sort)

# ── Generate Lua config module with all values baked in ──

lua_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

api_count=0
lua_keys=""
for var in ${api_var_names}; do
  val=$(printenv "${var}")
  if [ -n "${val}" ]; then
    if [ -n "${lua_keys}" ]; then
      lua_keys="${lua_keys}, "
    fi
    lua_keys="${lua_keys}\"$(lua_escape "${val}")\""
    api_count=$((api_count + 1))
  fi
done

local_key="${LOCAL_KEY:-my-secret-token}"
rate_limit_cooldown="${RATE_LIMIT_COOLDOWN:-60}"

# Validate RATE_LIMIT_COOLDOWN is a positive integer
case "${rate_limit_cooldown}" in
  ''|*[!0-9]*)
    echo "[ollagate] ERROR: RATE_LIMIT_COOLDOWN must be a positive integer, got: '${rate_limit_cooldown}'" >&2
    exit 1
    ;;
  0)
    echo "[ollagate] WARNING: RATE_LIMIT_COOLDOWN=0 means keys are re-enabled instantly" >&2
    ;;
esac

if [ "${METRICS_ENABLED}" = "true" ]; then
  lua_metrics="true"
else
  lua_metrics="false"
fi

if [ "${WEEKLY_LIMIT_COOLDOWN_MODE}" = "false" ]; then
  lua_weekly="false"
else
  lua_weekly="true"
fi

cat > "${CONFIG_LUA}" <<EOF
-- Auto-generated by entrypoint.sh — DO NOT EDIT
return {
  API_KEYS = {${lua_keys}},
  LOCAL_KEY = "$(lua_escape "${local_key}")",
  RATE_LIMIT_COOLDOWN = ${rate_limit_cooldown},
  METRICS_ENABLED = ${lua_metrics},
  WEEKLY_LIMIT_COOLDOWN_MODE = ${lua_weekly},
}
EOF

if [ "${api_count}" -eq 0 ]; then
  echo "[ollagate] WARNING: No API_KEY_* environment variables found." >&2
fi

# ── Start banner ──

echo ""
echo "  [ollagate] ${api_count} API key(s) loaded"
echo ""

# ── Start nginx ──

exec openresty -g 'daemon off;'